---
host: 172.16.10.30
username: root
# 使用private_key_file免密登录，则密码放空
password: 
del_logs:
      # true：递归目录删除日志文件、false：删除日志文件
    - is_del_dir: false
      # 文件或目录路径
      file_path: 
      # 要删除的文件后缀，不可为空（避免删除有用数据），仅当is_del_dir为true时生效，支持正则表达
      filename_suf: .log
      # 删除几天未操作的文件，-1：不做校验直接删除，n：多少天前
      del_how_day_ago: -1
      # 0：清空、1：删除。如果日志文件被程序运行占用，删除可能引发程序出错
      del_type: 0